### ISSUE TITLE
New isue

### ISSUE THREAD

**Issue by radiantcoders** [Rhythm-cmd/infinito2023#3]
Add badman again

**Comment by ManavTanna** [comment]
Can you describe the issue and assign it to me?

**Comment by Rhythm-cmd** [comment]
> Can you describe the issue and assign it to me?

Look for any kind of enhancement, I'll assign it to you.

**Comment by ManavTanna** [comment]
In the section where registration links are provided, rather than having just 2 containers, we can add 3 containers in a row...this would utilize the free space and also make the website look better

**Comment by Rhythm-cmd** [comment]
> In the section where registration links are provided, rather than having just 2 containers, we can add 3 containers in a row...this would utilize the free space and also make the website look better

Go ahead
